#!/bin/bash

LOCK_SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
source "${LOCK_SCRIPT_DIR}/logger.sh"

generate_lock() {
    local PROJECT_DIR="$1"
    local LOCKFILE
    local GENERATED_AT
    local GENERATED_BY
    local PROJECT_NAME
    local SERVICE
    local PORT_INDEX=1
    local PORT_VALUE
    local PORT_VALUES

    if [[ -z "$PROJECT_DIR" || ! -d "$PROJECT_DIR" ]]; then
        log_message "ERROR" "Invalid project directory: $PROJECT_DIR" || true
        return 107
    fi

    LOCKFILE="$PROJECT_DIR/envctr.lock"
    GENERATED_AT=$(date +"%Y-%m-%d-%H-%M-%S")
    GENERATED_BY=$(whoami)
    PROJECT_NAME=$(basename "$PROJECT_DIR")

    if ! {
        cat <<EOF
# envctr.lock
# Generated by envctr on $GENERATED_AT
# Do not edit manually.

[meta]
envctr_version = 1.0.0
project_name   = $PROJECT_NAME
generated_at   = $GENERATED_AT
generated_by   = $GENERATED_BY

[runtime]
language = ${DETECTED_RUNTIME:-}
version  = ${DETECTED_VERSION:-}
manager  = ${DETECTED_MANAGER:-}

[services]
EOF

        for SERVICE in ${DETECTED_SERVICES:-}; do
            printf '%s = detected\n' "$SERVICE"
        done

        cat <<EOF

[ports]
EOF

        if [[ -n "${DETECTED_PORTS:-}" ]]; then
            IFS=',' read -ra PORT_VALUES <<< "$DETECTED_PORTS"
            for PORT_VALUE in "${PORT_VALUES[@]}"; do
                if [[ "$PORT_INDEX" -eq 1 ]]; then
                    printf 'app = %s\n' "$PORT_VALUE"
                else
                    printf 'port_%s = %s\n' "$PORT_INDEX" "$PORT_VALUE"
                fi
                PORT_INDEX=$((PORT_INDEX + 1))
            done
        fi

        cat <<EOF

[environment]
required_vars = ${DETECTED_ENV_VARS:-}

[backend]
type = ${DETECTED_BACKEND:-${BACKEND:-}}
EOF
    } > "$LOCKFILE"; then
        log_message "ERROR" "Failed to write lockfile" || true
        return 107
    fi

    log_message "INFOS" "Lockfile written: $PROJECT_DIR/envctr.lock" || true
    return 0
}

parse_lock() {
    local PROJECT_DIR="$1"
    local LOCKFILE

    if [[ -z "$PROJECT_DIR" ]]; then
        log_message "ERROR" "Missing project directory or lockfile path" || true
        return 106
    fi

    LOCKFILE="$PROJECT_DIR/envctr.lock"
    if [[ -f "$PROJECT_DIR" && "$(basename "$PROJECT_DIR")" == "envctr.lock" ]]; then
        LOCKFILE="$PROJECT_DIR"
        PROJECT_DIR="$(dirname "$PROJECT_DIR")"
    fi

    if [[ ! -f "$LOCKFILE" ]]; then
        log_message "ERROR" "Lockfile not found" || true
        return 106
    fi

    LOCK_GENERATED_AT=$(grep -m1 -E '^generated_at[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_RUNTIME=$(grep -m1 -E '^language[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_VERSION=$(grep -m1 -E '^version[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_MANAGER=$(grep -m1 -E '^manager[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_SERVICES=$(awk -F '=' '
        /^\[services\]/ { active=1; next }
        /^\[/ { active=0 }
        active && /^[^#;[:space:]][^=]*=/ {
            key=$1; val=$2
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", key)
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", val)
            if (key == "detected") {
                print val
            } else if (val == "detected") {
                print key
            }
        }
    ' "$LOCKFILE" | xargs || true)
    LOCK_PORTS=$(awk -F '=' '
        /^\[ports\]/ { active=1; next }
        /^\[/ { active=0 }
        active && /^[^#;[:space:]][^=]*=/ {
            val=$2
            gsub(/^[[:space:]]+|[[:space:]]+$/, "", val)
            print val
        }
    ' "$LOCKFILE" | tr '\n' ',' | sed 's/,$//' || true)
    LOCK_ENV_VARS=$(grep -m1 -E '^required_vars[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_BACKEND=$(grep -m1 -E '^type[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)

    local missing_keys=()
    grep -qE '^generated_at[[:space:]]*=' "$LOCKFILE" || missing_keys+=("generated_at")
    grep -qE '^language[[:space:]]*=' "$LOCKFILE" || missing_keys+=("language")
    grep -qE '^version[[:space:]]*=' "$LOCKFILE" || missing_keys+=("version")
    grep -qE '^\[services\]' "$LOCKFILE" || missing_keys+=("services")
    grep -qE '^\[ports\]' "$LOCKFILE" || missing_keys+=("ports")
    grep -qE '^required_vars[[:space:]]*=' "$LOCKFILE" || missing_keys+=("required_vars")
    grep -qE '^type[[:space:]]*=' "$LOCKFILE" || missing_keys+=("type")

    if ((${#missing_keys[@]} > 0)); then
        log_message "ERROR" "Lockfile is missing required keys: ${missing_keys[*]}" || true
        return 106
    fi

    export LOCK_RUNTIME LOCK_VERSION LOCK_MANAGER LOCK_SERVICES LOCK_PORTS LOCK_ENV_VARS LOCK_BACKEND LOCK_GENERATED_AT

    log_message "INFOS" "Lockfile parsed: $PROJECT_DIR/envctr.lock" || true
    return 0
}
