#!/bin/bash

if [[ -f "$(dirname "$0")/logger.sh" ]]; then
    source "$(dirname "$0")/logger.sh"
else
    source "$(dirname "${BASH_SOURCE[0]}")/logger.sh"
fi

generate_lock() {
    local PROJECT_DIR="$1"
    if [[ -z "$PROJECT_DIR" || ! -d "$PROJECT_DIR" ]]; then  
        log_message "ERROR" "Invalid project directory: $PROJECT_DIR" || true  
        return 106  
    fi  
    local LOCKFILE="$PROJECT_DIR/envctr.lock"
    local GENERATED_AT
    local GENERATED_BY
    local PROJECT_NAME

    GENERATED_AT=$(date +"%Y-%m-%d-%H-%M-%S")
    GENERATED_BY=$(whoami)
    PROJECT_NAME=$(basename "$PROJECT_DIR")

    if ! cat > "$LOCKFILE" <<EOF
# envctr.lock
# Generated by envctr on $GENERATED_AT
# Do not edit manually.

[meta]
envctr_version = 1.0.0
project_name   = $PROJECT_NAME
generated_at   = $GENERATED_AT
generated_by   = $GENERATED_BY

[runtime]
language = ${DETECTED_RUNTIME:-}
version  = ${DETECTED_VERSION:-}

[services]
detected = ${DETECTED_SERVICES:-}

[ports]
detected = ${DETECTED_PORTS:-}

[environment]
required_vars = ${DETECTED_ENV_VARS:-}

[backend]
type = ${DETECTED_BACKEND:-${BACKEND:-}}
EOF
    then
        log_message "ERROR" "Failed to write lockfile" || true
        return 106
    fi

    log_message "INFOS" "Lockfile written: $PROJECT_DIR/envctr.lock" || true
    return 0
}


parse_lock() {
    local PROJECT_DIR="$1"
    if [[ -z "$PROJECT_DIR" ]]; then  
        log_message "ERROR" "Missing project directory or lockfile path" || true  
        return 106  
    fi  
    local LOCKFILE="$PROJECT_DIR/envctr.lock"

    if [[ -f "$PROJECT_DIR" && "$(basename "$PROJECT_DIR")" == "envctr.lock" ]]; then
        LOCKFILE="$PROJECT_DIR"
        PROJECT_DIR="$(dirname "$PROJECT_DIR")"
    fi

    if [[ ! -f "$LOCKFILE" ]]; then
        log_message "ERROR" "Lockfile not found" || true
        return 106
    fi

    LOCK_GENERATED_AT=$(grep -m1 -E '^generated_at[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//'|| true)
    LOCK_RUNTIME=$(grep -m1 -E '^language[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_VERSION=$(grep -m1 -E '^version[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_SERVICES=$(grep -A1 -E '^\[services\]' "$LOCKFILE" | grep -m1 -E '^detected[[:space:]]*=' | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_PORTS=$(grep -A1 -E '^\[ports\]' "$LOCKFILE" | grep -m1 -E '^detected[[:space:]]*=' | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_ENV_VARS=$(grep -m1 -E '^required_vars[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//' || true)
    LOCK_BACKEND=$(grep -m1 -E '^type[[:space:]]*=' "$LOCKFILE" | sed 's/^[^=]*=[[:space:]]*//; s/[[:space:]]*$//'|| true)
   
    local missing_keys=()  
    grep -qE '^generated_at[[:space:]]*=' "$LOCKFILE" || missing_keys+=("generated_at")  
    grep -qE '^language[[:space:]]*=' "$LOCKFILE" || missing_keys+=("language")  
    grep -qE '^version[[:space:]]*=' "$LOCKFILE" || missing_keys+=("version")  
    grep -A1 -E '^\[services\]' "$LOCKFILE" | grep -qE '^detected[[:space:]]*=' || missing_keys+=("services.detected")  
    grep -A1 -E '^\[ports\]' "$LOCKFILE" | grep -qE '^detected[[:space:]]*=' || missing_keys+=("ports.detected")  
    grep -qE '^required_vars[[:space:]]*=' "$LOCKFILE" || missing_keys+=("required_vars")  
    grep -qE '^type[[:space:]]*=' "$LOCKFILE" || missing_keys+=("type")  
  
    if ((${#missing_keys[@]} > 0)); then
        log_message "ERROR" "Lockfile is missing required keys: ${missing_keys[*]}" || true   
        return 106  
    fi  
    export LOCK_RUNTIME LOCK_VERSION LOCK_SERVICES LOCK_PORTS LOCK_ENV_VARS LOCK_BACKEND LOCK_GENERATED_AT

    log_message "INFOS" "Lockfile parsed: $PROJECT_DIR/envctr.lock" || true
    return 0
}
